// const promise = new Promise((resolve, reject)=>{

//     setTimeout(()=>{
//         resolve('this is my resolved data');
//         // reject('something when wrong here')
//     },2000);

    
// });


// promise.then((data)=>{
//  console.log(data)
//     new Promise((resolve, reject)=>{
//         resolve('you are in the second promise')
//     }).then((second)=>{
//         console.log(second)
//     })
// }).catch((error)=>{
//     console.log(error)
// });

